[package]
name = "dtls-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.64"
threadpool = "1.8.1"
tokio = { version = "1", features = ["full"] }
bytes = "1"
byteorder = "1.5.0"
